version: '3'
services:

  mystrapiDB:
    container_name: mystrapiDB
    restart: "no"
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - mystrapi-data:/var/lib/postgresql/data/

    ports:
      - '5432:5432'

volumes:
  mystrapi-data:
